Skip to content
Search or jump to…

Pull requests
Issues
Marketplace
Explore
 
@razevedo76 
analiairigoyen
/
YAML
2
515
Code
Issues
Pull requests
Actions
Projects
Wiki
Security
Insights
YAML/WEbYAML.txt
@analiairigoyen
analiairigoyen Add files via upload
Latest commit 2e2e257 on 21 Aug
 History
 1 contributor
56 lines (43 sloc)  1.47 KB
  
# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

# Command line
# Run a command line script using Bash on Linux and macOS and cmd.exe on Windows

- task: CmdLine@2
  inputs:
    script: 'mkdir d:\a\1\MobEAD' 
    #workingDirectory: # Optional
    #failOnStderr: false # Optional

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DeployIisAppPath="Default Web Site" /p:DesktopBuildPackageLocation="d:\a\1\mobEAD"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'


- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    testAssemblyVer2: '$(Build.SourcesDirectory)/test**.js'
 
- task: CopyFiles@2
  inputs:
    contents: '**/*.*'
    targetFolder: $(build.artifactStagingDirectory)

- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'MobEAD'
    pathToPublish: 'd:\a\1\a'
© 2020 GitHub, Inc.
Terms
Privacy
Security
Status
Help
Contact GitHub
Pricing
API
Training
Blog
About
